### PR TITLE
update to 0.20

### PR DESCRIPTION
**Pull request by blakeanedved**
Examples didn't get updated to 0.20 when it released, I just copied the examples straight from the upstream repo.

### CODE REVIEW

**Comment by cultofmetatron** [comment]
👍   Came here as a newbie rust dev. The main example repo completely fails to build but I can confirm this fork builds and runs without issue on the latest osx sierra with the latest Vulkan drivers.

Thankyou @blakeanedved

**Comment by jamestmartin** [comment]
Likewise for Debian bullseye.

**Comment by gyant** [comment]
Thanks @blakeanedved your fork works with BigSur and the latest version of Vulkan API. ❤️

**Comment by Gorgonx7** [comment]
Can confirm, this also runs on windows and fixes the build issues I was having too

**Comment by damien-lloyd** [comment]
I can also confirm this fixes the build issues on my Manjaro installation. Nice to see it also working on Windows, macOS and other Linux distros too :-)

**Comment by Eliah-Lakhin** [comment]
@blakeanedved and everyone, thank you for updating the examples subproject!

I totally forget about keeping it up to date. We also have duplicates of examples in the main repo: https://github.com/vulkano-rs/vulkano/tree/master/examples that I'm trying to keep consistent with the main codebase more regularly.

But I will keep an eye for "vulkano-example" too.

Thanks again!

**Pull request merged**
